namespace PalOps.Tooling.Catalog;

internal static class CatalogRules
{
    public static readonly IReadOnlyDictionary<string, string> ItemExact =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["AnimalSkin"] = "兽皮",
            ["AnimalSkin2"] = "优质兽皮",
            ["Scales"] = "鳞片",
            ["Scales2"] = "优质鳞片",
            ["Axe_Tier_03"] = "高级斧",
            ["Berries2"] = "优质浆果",
            ["CaptureRope"] = "捕获绳",
            ["Claws"] = "爪",
            ["Claws2"] = "优质爪",
            ["ClawsPendant"] = "爪牙吊坠",
            ["ClothHat"] = "布帽",
            ["ElectronicCircuit"] = "电子电路",
            ["EnergyDrink"] = "能量饮料",
            ["Fang"] = "獠牙",
            ["Fang2"] = "优质獠牙",
            ["FangNecklace"] = "獠牙项链",
            ["FarmCrop_Tmp"] = "开发测试：农作物",
            ["FishMeat"] = "鱼肉",
            ["FishMeat2"] = "优质鱼肉",
            ["Flint"] = "燧石",
            ["Gunpowder"] = "火药",
            ["IronOre"] = "铁矿石",
            ["Kitsunebi_Fire"] = "火属性焰狐素材",
            ["LargeBullet"] = "大口径弹药",
            ["Launcher_Meat"] = "肉块发射器",
            ["Leather2"] = "优质皮革",
            ["Meat2"] = "优质肉",
            ["PalSphere_Debug"] = "开发测试：帕鲁球",
            ["PenguinLauncher"] = "企丸丸发射器",
            ["Pickaxe_Tier_03"] = "高级镐",
            ["SniperRifle_Default"] = "制式狙击步枪",
            ["Seed_Tmp"] = "开发测试：种子",
            ["Sharkkid_Scale"] = "鲨小子鳞片",
            ["SmallBullet"] = "小口径弹药",
            ["PAL_Growth_Stone_S"] = "小型帕鲁成长石",
            ["PAL_Growth_Stone_M"] = "中型帕鲁成长石",
            ["PAL_Growth_Stone_L"] = "大型帕鲁成长石",
            ["PAL_Growth_Stone_XL"] = "特大型帕鲁成长石",
            ["ThrowStone"] = "投掷石",
            ["VenisonBoiledInTomato"] = "番茄炖鹿肉",
            ["WaterBucket"] = "水桶",
            ["RecurveBow"] = "反曲弓",
            ["PotatoSeedPotatoes"] = "种薯",
            ["Potato_old"] = "旧版马铃薯",
            ["Corn"] = "玉米",
            ["Pumpkin"] = "南瓜",
            ["Baked_Potato"] = "烤马铃薯",
            ["Grape"] = "葡萄",
            ["Hop"] = "啤酒花",
            ["Curry_old"] = "旧版咖喱",
            ["Sandwich"] = "三明治",
            ["CornSoup"] = "玉米浓汤",
            ["Stew"] = "炖菜",
            ["GrilledFish"] = "烤鱼",
            ["SeafoodSoup"] = "海鲜汤",
            ["LuxuryOmelette"] = "豪华煎蛋卷",
            ["Beer"] = "啤酒",
            ["Wine"] = "葡萄酒",
            ["Antibiotic_Normal"] = "普通抗生素",
            ["Antibiotic_Good"] = "优质抗生素",
            ["Antibiotic_Super"] = "高级抗生素",
            ["FishingRod_Old"] = "旧式钓竿",
            ["FishingRod_Good"] = "优质钓竿",
            ["FishingRod_Super"] = "高级钓竿",
            ["FishingRod_Legendary"] = "传说钓竿",
            ["Glider_Legendary"] = "传说滑翔伞",
            ["PV_Glider_Manta"] = "天擒鸟滑翔装置",
            ["LightzHelmet"] = "照明头盔",
            ["NightVisionGoggles"] = "夜视镜",
            ["CashFang"] = "可出售的獠牙",
            ["CashScales"] = "可出售的鳞片",
            ["AirGrapplingGun"] = "空中抓钩枪",
            ["Sand"] = "沙子",
            ["Gasoline"] = "汽油",
            ["Accessory_AirDash4"] = "四段空中冲刺靴",
            ["Otomo_MoveSpeed_up_1"] = "伙伴移动速度强化 I",
            ["YakushimaParts001"] = "樱岛零件 I",
            ["YakushimaParts002"] = "樱岛零件 II",
            ["YakushimaParts003"] = "樱岛零件 III",
            ["PalEgg_MutationPal"] = "巨大突变帕鲁蛋",
            ["SkillUnlock_BlackFurDragon"] = "黑毛龙专属霰弹枪",
            ["SkillUnlock_DarkMutant"] = "暗影异变体动力转换器",
            ["Blueprint_HeadEquip025_5"] = "头部装备 025 设计图（内部）",
            ["Blueprint_HeadEquip026_5"] = "头部装备 026 设计图（内部）",
            ["Blueprint_HeadEquip028_5"] = "头部装备 028 设计图（内部）",
            ["Blueprint_HeadEquip031_5"] = "头部装备 031 设计图（内部）",
            ["Blueprint_HeadEquip032_5"] = "头部装备 032 设计图（内部）",
            ["BelieverFatCane"] = "信徒粗手杖（NPC 内部武器）",
            ["BelieverFatCane_Otomo"] = "信徒粗手杖（伙伴内部武器）",
            ["Debug_Handgun_IvyCling"] = "开发测试：缠藤效果手枪",
            ["PalGenderReverseTest"] = "开发测试：帕鲁性别反转道具",
            ["PalPassiveSkillChangeTest"] = "开发测试：帕鲁被动技能变更道具",
            ["PalPassiveSkillChangeTest2"] = "开发测试：帕鲁被动技能变更道具 II",
            ["TEST_BossDefeatReward"] = "开发测试：首领奖励",
            ["Blueprint_Salvage_TreasureBoxKey01"] = "打捞宝箱钥匙设计图",
            ["PalAwakening_Test"] = "开发测试：帕鲁觉醒道具",
            ["PalPassiveSkillChange_SwimSpeed_ConsumeTest"] = "开发测试：游泳速度被动变更道具",
            ["WingGlider_Test"] = "开发测试：翼型滑翔装置"
        };

    public static readonly IReadOnlyDictionary<string, string> PalExact =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["ElecLion"] = "雷狮",
            ["PinkKangaroo"] = "粉袋鼠",
            ["BeardedDragon"] = "须龙",
            ["WaterLizard"] = "水蜥蜴",
            ["GrassDragon"] = "草龙",
            ["BlackFurDragon"] = "黑毛龙",
            ["Monkey_Ice"] = "冰猿",
            ["DarkMutant"] = "暗影异变体",
            ["KingCrab"] = "帝王蟹",
            ["ElecSnail_Fire"] = "火焰电蜗牛",
            ["StrawHatCat"] = "草帽猫",
            ["CandleWitch"] = "烛火魔女",
            ["FrozenBear"] = "冻原熊",
            ["VolcanicTurtle"] = "火山龟",
            ["IceVeilDragon"] = "冰幕龙",
            ["BlueWoolRabbit"] = "蓝绒兔",
            ["MonochromeMushroom"] = "墨色蘑菇",
            ["MedjedBird"] = "梅杰德鸟",
            ["RockCheetah"] = "岩猎豹",
            ["ArmorWoodlouse"] = "铠甲潮虫",
            ["MexicanSalamander"] = "墨西哥钝口螈",
            ["LeafBird"] = "叶羽鸟",
            ["CuteOrca"] = "萌虎鲸",
            ["SnakeQueen"] = "蛇后",
            ["TestNPC"] = "开发测试 NPC",
            ["QuestMan"] = "任务委托人",
            ["TestAssassin"] = "开发测试刺客"
        };

    public static readonly IReadOnlyDictionary<string, string> ItemCategoryExact =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["MeatCutterKnife"] = "武器与工具",
            ["Meat_GrassMammoth"] = "食物",
            ["BakedMeat_GrassMammoth"] = "食物",
            ["Yakisoba"] = "食物",
            ["Meat_SwordCutlassFish"] = "食物",
            ["GrilledSwordCutlassFish"] = "食物"
        };

    public static readonly string[] HumanIdPrefixes =
    [
        "HUNTER_", "POLICE_", "FIRECULT_", "BELIEVER_", "SCIENTIST_",
        "MALE_", "FEMALE_", "MOBU", "SALESPERSON", "VISITINGMERCHANT",
        "WEAPONSDEALER", "PALDEALER", "INSPECTOR", "PALTRADER",
        "GOODWILLAMBASSADOR", "ROBBERY_", "VISITOR_", "RANDOMEVENTSHOP",
        "GUARD_", "NINJA", "VIKING", "ESCORT_", "ARENA_", "REWARD_",
        "EMOTE_", "HELP", "NPC_", "BOUNTYTRADER", "EPICURE", "DOCTOR",
        "PALPASSIVE_DOCTOR", "CARAVANLEADER", "SORAJIMATOWERGUIDE"
    ];

    public static readonly string[] HumanEnglishFragments =
    [
        "syndicate ", "pidf ", "islander", "villager", "merchant", "dealer",
        "black marketeer", "brothers of the eternal pyre", "free pal alliance",
        "pal genetic research unit", "moonflower ", "mercenary", "pal tamer",
        "researcher", "recruiter", "bodyguard", "feybreak warrior",
        "feybreak berserker", "caravan leader", "guard", "presenter"
    ];

    public static readonly IReadOnlyDictionary<string, string> TokenZh =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["assault"] = "突击",
            ["rifle"] = "步枪",
            ["handgun"] = "手枪",
            ["shotgun"] = "霰弹枪",
            ["laser"] = "激光",
            ["rocket"] = "火箭",
            ["missile"] = "导弹",
            ["grenade"] = "榴弹",
            ["launcher"] = "发射器",
            ["gatling"] = "加特林",
            ["flame"] = "火焰",
            ["thrower"] = "喷射器",
            ["frag"] = "破片",
            ["bat"] = "球棒",
            ["bow"] = "弓",
            ["gun"] = "枪",
            ["katana"] = "武士刀",
            ["beam"] = "光束",
            ["sword"] = "剑",
            ["poison"] = "中毒",
            ["burn"] = "燃烧",
            ["wetness"] = "潮湿",
            ["freeze"] = "冻结",
            ["electrical"] = "感电",
            ["muddy"] = "泥泞",
            ["darkness"] = "黑暗",
            ["stun"] = "眩晕",
            ["attack"] = "攻击",
            ["defense"] = "防御",
            ["up"] = "提升",
            ["blueprint"] = "设计图",
            ["head"] = "头部",
            ["equip"] = "装备",
            ["salvage"] = "打捞",
            ["treasure"] = "宝箱",
            ["box"] = "箱",
            ["key"] = "钥匙",
            ["fishing"] = "钓鱼",
            ["bait"] = "鱼饵",
            ["pal"] = "帕鲁",
            ["passive"] = "被动",
            ["skill"] = "技能",
            ["change"] = "变更",
            ["consume"] = "消耗",
            ["test"] = "测试",
            ["awakening"] = "觉醒",
            ["gender"] = "性别",
            ["reverse"] = "反转",
            ["confidence"] = "亲密度",
            ["increase"] = "提升",
            ["wing"] = "翼",
            ["glider"] = "滑翔装置",
            ["growth"] = "成长",
            ["stone"] = "石",
            ["boss"] = "首领",
            ["reward"] = "奖励",
            ["npc"] = "NPC",
            ["otomo"] = "伙伴",
            ["grass"] = "草系",
            ["default"] = "制式",
            ["old"] = "旧版",
            ["tier"] = "等级"
        };
}
