using Wasmtime;

namespace PalOps.Web.SaveGames.Binary;

/// <summary>
/// Decompresses Palworld 1.0 PlM1 payloads through the GPL open-source ooz
/// decoder embedded in this assembly. No proprietary Oodle DLL, Python
/// process, Node.js process, or Palworld installation is required at runtime.
/// </summary>
public interface IPalworldOozDecoder
{
    Task<byte[]> DecompressAsync(
        ReadOnlyMemory<byte> compressed,
        int expectedLength,
        CancellationToken cancellationToken = default);
}

/// <summary>
/// Hosts the Emscripten-built ooz WebAssembly module with Wasmtime.
///
/// The module exposes the same Kraken_Decompress entry point used by the
/// PalworldSaveTools/palooz path. One module instance owns one allocator and
/// one linear memory, so calls are serialized through <see cref="SemaphoreSlim"/>.
/// </summary>
public sealed class PalworldOozDecoder : IPalworldOozDecoder, IDisposable
{
    private const string ModuleResourceName = "PalOps.Web.SaveGames.Binary.Native.ooz.wasm";
    private const int OozSafeSpaceBytes = 64;
    private const long WebAssemblyPageSize = 64 * 1024;

    // Export names are generated by the published ooz-wasm 2.0.0 Emscripten build.
    private const string MemoryExport = "c";
    private const string ConstructorsExport = "d";
    private const string MallocExport = "e";
    private const string FreeExport = "f";
    private const string DecompressExport = "g";

    private readonly ILogger<PalworldOozDecoder> _logger;
    private readonly SemaphoreSlim _gate = new(1, 1);
    private readonly Engine _engine;
    private readonly Module _module;
    private readonly Store _store;
    private readonly Linker _linker;
    private readonly Memory _memory;
    private readonly Func<int, int> _malloc;
    private readonly Action<int> _free;
    private readonly Func<int, int, int, int, int> _decompress;
    private bool _disposed;

    public PalworldOozDecoder(ILogger<PalworldOozDecoder> logger)
    {
        _logger = logger;

        try
        {
            _engine = new Engine();
            _module = Module.FromBytes(_engine, "palops-ooz", ReadEmbeddedModule());
            _store = new Store(_engine);
            _linker = new Linker(_engine);

            // Import a.a = _emscripten_resize_heap(requestedSize) -> success flag.
            _linker.DefineFunction(
                "a",
                "a",
                new CallerFunc<int, int>(ResizeHeap));

            // Import a.b = _emscripten_memcpy_js(destination, source, length).
            _linker.DefineFunction(
                "a",
                "b",
                new CallerAction<int, int, int>(CopyMemory));

            var instance = _linker.Instantiate(_store, _module);
            _memory = instance.GetMemory(MemoryExport)
                      ?? throw new InvalidOperationException("内置 ooz 模块未导出线性内存。");

            var constructors = instance.GetAction(ConstructorsExport)
                               ?? throw new InvalidOperationException("内置 ooz 模块未导出初始化函数。");
            _malloc = instance.GetFunction<int, int>(MallocExport)
                      ?? throw new InvalidOperationException("内置 ooz 模块未导出 malloc。");
            _free = instance.GetAction<int>(FreeExport)
                    ?? throw new InvalidOperationException("内置 ooz 模块未导出 free。");
            _decompress = instance.GetFunction<int, int, int, int, int>(DecompressExport)
                          ?? throw new InvalidOperationException("内置 ooz 模块未导出 Kraken_Decompress。");

            constructors();
            _logger.LogInformation(
                "Initialized bundled GPL ooz decoder from embedded resource {ResourceName}.",
                ModuleResourceName);
        }
        catch (Exception ex)
        {
            throw new InvalidOperationException(
                "内置 PlM1/ooz 解码器初始化失败。请确认发布目录包含 Wasmtime 对应平台运行库，" +
                "并且项目使用完整的 dotnet publish 输出。",
                ex);
        }
    }

    public async Task<byte[]> DecompressAsync(
        ReadOnlyMemory<byte> compressed,
        int expectedLength,
        CancellationToken cancellationToken = default)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        if (compressed.IsEmpty) throw new InvalidDataException("PlM1/ooz 压缩数据为空。");
        if (expectedLength <= 0) throw new InvalidDataException("PlM1/ooz 解压目标长度无效。");
        if (compressed.Length > int.MaxValue)
            throw new InvalidDataException("PlM1/ooz 压缩数据超过 WebAssembly 32 位地址空间限制。");
        if (expectedLength > int.MaxValue - OozSafeSpaceBytes)
            throw new InvalidDataException("PlM1/ooz 解压目标超过 WebAssembly 32 位地址空间限制。");

        await _gate.WaitAsync(cancellationToken).ConfigureAwait(false);
        try
        {
            cancellationToken.ThrowIfCancellationRequested();
            return DecompressCore(compressed.Span, expectedLength, cancellationToken);
        }
        finally
        {
            _gate.Release();
        }
    }

    private byte[] DecompressCore(
        ReadOnlySpan<byte> compressed,
        int expectedLength,
        CancellationToken cancellationToken)
    {
        var compressedPointer = 0;
        var outputPointer = 0;

        try
        {
            compressedPointer = Allocate(compressed.Length, "压缩输入");
            outputPointer = Allocate(checked(expectedLength + OozSafeSpaceBytes), "解压输出");

            ValidateRange(compressedPointer, compressed.Length, "压缩输入");
            compressed.CopyTo(_memory.GetSpan(compressedPointer, compressed.Length));

            cancellationToken.ThrowIfCancellationRequested();
            var decodedLength = _decompress(
                compressedPointer,
                compressed.Length,
                outputPointer,
                expectedLength);
            cancellationToken.ThrowIfCancellationRequested();

            if (decodedLength < 0)
                throw new InvalidDataException($"PlM1/ooz 解压失败，Kraken_Decompress 返回 {decodedLength}。");
            if (decodedLength != expectedLength)
                throw new InvalidDataException(
                    $"PlM1/ooz 解压长度不匹配：期望 {expectedLength:N0}，实际 {decodedLength:N0}。");

            ValidateRange(outputPointer, expectedLength, "解压输出");
            return _memory.GetSpan(outputPointer, expectedLength).ToArray();
        }
        catch (InvalidDataException)
        {
            throw;
        }
        catch (OperationCanceledException)
        {
            throw;
        }
        catch (Exception ex)
        {
            throw new InvalidDataException(
                "PlM1/ooz 解压失败。内置 GPL 解码器发生 WebAssembly 陷阱或内存错误。",
                ex);
        }
        finally
        {
            if (compressedPointer != 0) TryFree(compressedPointer);
            if (outputPointer != 0) TryFree(outputPointer);
        }
    }

    private int Allocate(int byteCount, string purpose)
    {
        if (byteCount <= 0) throw new InvalidDataException($"{purpose}分配长度无效。");
        var pointer = _malloc(byteCount);
        if (pointer == 0)
            throw new InvalidDataException($"内置 ooz 解码器无法为{purpose}分配 {byteCount:N0} 字节。");

        ValidateRange(pointer, byteCount, purpose);
        return pointer;
    }

    private void TryFree(int pointer)
    {
        try
        {
            _free(pointer);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Failed to free ooz WebAssembly allocation at {Pointer}.", pointer);
        }
    }

    private void ValidateRange(int pointer, int length, string purpose)
    {
        if (pointer < 0 || length < 0)
            throw new InvalidDataException($"内置 ooz 解码器返回了无效的{purpose}内存范围。");

        var end = (long)pointer + length;
        var memoryLength = _memory.GetLength();
        if (end > memoryLength)
            throw new InvalidDataException(
                $"内置 ooz 解码器的{purpose}内存越界：范围 {pointer:N0}..{end:N0}，" +
                $"当前内存 {memoryLength:N0} 字节。");
    }

    private static int ResizeHeap(Caller caller, int requestedSize)
    {
        // Emscripten passes the requested heap size as wasm i32. The ooz build
        // deliberately caps the heap at 2 GiB, so a negative signed value is invalid.
        if (requestedSize <= 0)
            return 0;

        var memory = caller.GetMemory(MemoryExport)
                     ?? throw new InvalidOperationException("ooz 模块在扩容时无法访问线性内存。");
        var currentLength = memory.GetLength();
        if (requestedSize <= currentLength) return 1;

        var missingBytes = requestedSize - currentLength;
        var pages = checked((missingBytes + WebAssemblyPageSize - 1) / WebAssemblyPageSize);
        try
        {
            memory.Grow(pages);
            return memory.GetLength() >= requestedSize ? 1 : 0;
        }
        catch
        {
            return 0;
        }
    }

    private static void CopyMemory(Caller caller, int destination, int source, int length)
    {
        if (destination < 0 || source < 0 || length < 0)
            throw new InvalidOperationException("ooz memcpy 收到负数内存参数。");

        var memory = caller.GetMemory(MemoryExport)
                     ?? throw new InvalidOperationException("ooz 模块在复制时无法访问线性内存。");
        var memoryLength = memory.GetLength();
        var sourceEnd = (long)source + length;
        var destinationEnd = (long)destination + length;
        if (sourceEnd > memoryLength || destinationEnd > memoryLength)
            throw new InvalidOperationException("ooz memcpy 超出 WebAssembly 线性内存范围。");

        // Span.CopyTo has memmove semantics for overlapping source/destination ranges.
        memory.GetSpan(source, length).CopyTo(memory.GetSpan(destination, length));
    }

    private static byte[] ReadEmbeddedModule()
    {
        var assembly = typeof(PalworldOozDecoder).Assembly;
        using var stream = assembly.GetManifestResourceStream(ModuleResourceName)
                           ?? throw new FileNotFoundException(
                               $"程序集缺少内置 ooz 模块资源：{ModuleResourceName}。");
        using var buffer = new MemoryStream(capacity: checked((int)stream.Length));
        stream.CopyTo(buffer);
        var bytes = buffer.ToArray();
        if (bytes.Length < 8 || !bytes.AsSpan(0, 4).SequenceEqual("\0asm"u8))
            throw new InvalidDataException("内置 ooz 模块不是有效的 WebAssembly 文件。");
        return bytes;
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        _gate.Dispose();
        _linker.Dispose();
        _store.Dispose();
        _module.Dispose();
        _engine.Dispose();
    }
}
